IF (OBJECT_ID('FooTable') IS NOT NULL)
BEGIN
    DROP TABLE FooTable
END

CREATE TABLE FooTable (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    DateOfBirth DATETIME
)