DROP TABLE DB2ADMIN.FOOTABLE;

CREATE TABLE DB2ADMIN.FOOTABLE (
    FOOID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
    "FIRST" NVARCHAR(50),
    "LAST" NVARCHAR(50),
    BIRTHDATE DATE
);