DROP TABLE DB2ADMIN.MULTIKEY;

CREATE TABLE DB2ADMIN.MULTIKEY (
    KEY1 INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    KEY2 NVARCHAR(50) NOT NULL,
    VALUE NVARCHAR(50),
    PRIMARY KEY(KEY1, KEY2)
);